server:
  port: 8081


spring:
  datasource:
    username: root
    data-password: root
    url: jdbc:mysql://localhost:3306/vhr
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource