spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vhr
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081